package io.gateway.persistence

import com.zaxxer.hikari.HikariConfig
import com.zaxxer.hikari.HikariDataSource
import org.flywaydb.core.Flyway
import org.jetbrains.exposed.v1.jdbc.Database
import javax.sql.DataSource

/**
 * Owns the connection pool and schema lifecycle. Flyway applies versioned SQL
 * migrations on startup; Exposed is bound to the same pooled [DataSource].
 * DDL is never generated by Exposed in production — migrations are the source of truth.
 */
class DatabaseFactory(private val config: DatabaseConfig) {

    private lateinit var dataSource: HikariDataSource

    /**
     * Opens the pool, runs migrations, and registers the connection as Exposed's
     * default database (so suspended transactions resolve it implicitly).
     */
    fun connect() {
        dataSource = HikariDataSource(hikariConfig())
        migrate(dataSource)
        Database.connect(dataSource)
    }

    fun close() {
        if (::dataSource.isInitialized) dataSource.close()
    }

    private fun hikariConfig(): HikariConfig = HikariConfig().apply {
        jdbcUrl = config.jdbcUrl
        username = config.username
        password = config.password
        driverClassName = config.driverClassName
        maximumPoolSize = config.maxPoolSize
        isAutoCommit = false
        transactionIsolation = "TRANSACTION_REPEATABLE_READ"
        validate()
    }

    private fun migrate(ds: DataSource) {
        Flyway.configure()
            .dataSource(ds)
            .locations("classpath:db/migration")
            .load()
            .migrate()
    }
}
